services:
  app:
    image: "khemlabs/corvus-frontend:${TAG:-latest}"
    env_file: "./.env"
    build:
      context: ./
      args:
        APP_PORT: "${PORT:-3000}"
      target: runner
    networks:
      - frontend
    restart: always

networks:
  frontend:
    name: "${NETWORK_NAME:-corvus-network}"
    driver: "${NETWORK_DRIVER:-overlay}"
